#ifndef LTJS_COMPILER_HPP
#define LTJS_COMPILER_HPP

enum class token : int {
	END_OF_FILE, ASSIGNMENT, CLASS, DEF,
	ELSE, EXTENDS, IDENTIFIER, IF, INTEGER,
	IS, MINUS, NEW, OBJECT, OVERRIDE, PLUS,
	POINT, RELATIONAL_OPERATOR, RETURN,
	SLASH, STAR, THEN, VAR
};

enum class operation : int {
	/* MISCELLANEOUS */
	TERNARY_CONDITIONAL,
	/* ARITHMETIC */
	UNARY_PLUS, UNARY_SUBSTRACT,
	MULTIPLICATION, DIVISION,
	ADDITION, SUBSTRACTION,
	/* RELATIONAL_OPERATOR */
	LESS_STRICT, LESS_EQUAL, GREATER_STRICT, GREATER_EQUAL,
	EQUAL, NOT_EQUAL
};



/* AST definition */
#include "utils/tree.hpp"

/* YYSTYPE defintion */
#include <string>
#include <variant>

typedef std::variant<int, std::string> YYSTYPE;

#define YYSTYPE YYSTYPE

#endif